name: "Deployment"
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer Install
        uses: MilesChou/composer-action@v1.0.2
        with:
          args: install --working-dir=./src/
      - run: ls -la ./ ./src
      - name: Deploy to Cotya server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          ARGS: "-rltgoDzvO"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/html/github_deploy/build


