name: "Deployment"
on:
  push:

jobs:
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./
      - run: tar -xjvf build.tar.bz2
      - run: ls -la ./ ./src
      - name: Deploy to Cotya server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          ARGS: "-rltgoDzvO"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/html/github_deploy/build
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer Install
        uses: MilesChou/composer-action@v1.0.2
        with:
          args: install --working-dir=./src/
      - run: tar -cjvf build.tar.bz2 ./src
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.tar.bz2


