name: "Deployment"
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer Install
        uses: php-actions/composer@v2
        with:
          command: install
          only_args: --working-dir=./src/
      - run: cd ./src && bash scripts/removeParts.sh
      - run: ls -la ./ ./src
      - name: Deploy to Cotya server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          ARGS: "-rltgoDzvO"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/html/github_deploy/build_${{ github.run_number }}
      - name: set symlink
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          script: cd /var/www/html/github_deploy/build_${{ github.run_number }} && rm -rf htdocs/media htdocs/app/etc && ln -nsf $(realpath ../../shared-files/media) htdocs/media &&  ln -nsf $(realpath ../../shared-files/etc) htdocs/app/etc
      - name: clean build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          script: cd /var/www/html/github_deploy/build_${{ github.run_number }} && bash scripts/removeParts.sh
      - name: set symlink
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          script: ln -nsf /var/www/html/github_deploy/build_${{ github.run_number }} /var/www/html/github_latest
      - name: clean old deployments
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.OPENMAGE_DEMO_DEPLOY_RSA }}
          script: cd /var/www/html/github_deploy/ && ls -t | tail -n +4 | xargs rm -r --

