name: "Deployment"
on:
  push:

jobs:
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build
      - name: Run a one-line script
        run: ls -la ./ ./build

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Composer Action
        uses: MilesChou/composer-action@v1.0.2
        with:
          args: install --working-dir=./src/
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: src


